#!/bin/bash

# =============================================================================
# Loko Backend Management Script
# =============================================================================
# Script untuk mengelola project Loko Backend tanpa Docker
# Author: Generated by AI Assistant
# Version: 1.0
# =============================================================================

# Warna untuk output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Konfigurasi
APP_NAME="loko-backend"
BINARY_NAME="app"
LOG_DIR="logs"
TEMP_DIR="temp"
PID_FILE="${APP_NAME}.pid"
LOG_FILE="${LOG_DIR}/${APP_NAME}.log"
ERROR_LOG="${LOG_DIR}/${APP_NAME}_error.log"
ACCESS_LOG="${LOG_DIR}/${APP_NAME}_access.log"

# =============================================================================
# Utility Functions
# =============================================================================

# Fungsi untuk menampilkan banner
show_banner() {
    echo -e "${CYAN}"
    echo "============================================="
    echo "    LOKO BACKEND MANAGEMENT SCRIPT"
    echo "============================================="
    echo -e "${NC}"
}

# Fungsi untuk logging
log() {
    local level=$1
    shift
    local message="$*"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    
    case $level in
        "INFO")
            echo -e "${GREEN}[INFO]${NC} $message"
            echo "[$timestamp] [INFO] $message" >> "$LOG_FILE"
            ;;
        "WARN")
            echo -e "${YELLOW}[WARN]${NC} $message"
            echo "[$timestamp] [WARN] $message" >> "$LOG_FILE"
            ;;
        "ERROR")
            echo -e "${RED}[ERROR]${NC} $message"
            echo "[$timestamp] [ERROR] $message" >> "$ERROR_LOG"
            ;;
        "DEBUG")
            echo -e "${BLUE}[DEBUG]${NC} $message"
            echo "[$timestamp] [DEBUG] $message" >> "$LOG_FILE"
            ;;
    esac
}

# Fungsi untuk mengecek apakah aplikasi sedang berjalan
is_running() {
    if [ -f "$PID_FILE" ]; then
        local pid=$(cat "$PID_FILE")
        if ps -p "$pid" > /dev/null 2>&1; then
            return 0
        else
            rm -f "$PID_FILE"
            return 1
        fi
    fi
    return 1
}

# Fungsi untuk membuat direktori yang diperlukan
setup_directories() {
    log "INFO" "Membuat direktori yang diperlukan..."
    mkdir -p "$LOG_DIR"
    mkdir -p "$TEMP_DIR"
    mkdir -p "docs"
}

# Fungsi untuk mengecek dependencies
check_dependencies() {
    log "INFO" "Mengecek dependencies..."
    
    # Cek Go
    if ! command -v go &> /dev/null; then
        log "ERROR" "Go tidak terinstall. Silakan install Go terlebih dahulu."
        exit 1
    fi
    
    local go_version=$(go version | awk '{print $3}' | sed 's/go//')
    log "INFO" "Go version: $go_version"
    
    # Cek swag untuk Swagger
    if ! command -v swag &> /dev/null; then
        log "WARN" "Swag tidak terinstall. Install dengan: go install github.com/swaggo/swag/cmd/swag@latest"
    fi
}

# =============================================================================
# Build Functions
# =============================================================================

# Fungsi untuk build aplikasi (native)
build() {
    log "INFO" "Memulai proses build native..."
    
    # Cek syntax error terlebih dahulu
    log "INFO" "Mengecek syntax Go..."
    if ! go vet ./...; then
        log "ERROR" "Ditemukan error dalam kode Go!"
        return 1
    fi
    
    # Build aplikasi
    log "INFO" "Building aplikasi..."
    if go build -o "$BINARY_NAME" .; then
        log "INFO" "Build berhasil! Binary: $BINARY_NAME"
        return 0
    else
        log "ERROR" "Build gagal!"
        return 1
    fi
}

# Fungsi untuk build frontend React dengan Bun
build_frontend() {
    log "INFO" "🚀 Building React Frontend with Bun..."
    
    # Cek apakah direktori frontend ada
    if [ ! -d "frontend" ]; then
        log "ERROR" "Direktori frontend tidak ditemukan!"
        return 1
    fi
    
    # Cek apakah Bun terinstall
    if ! command -v bun &> /dev/null; then
        log "ERROR" "Bun tidak terinstall! Install dengan: curl -fsSL https://bun.sh/install | bash"
        return 1
    fi
    
    # Navigate to frontend directory
    local current_dir=$(pwd)
    cd frontend
    
    # Check if node_modules exists, if not install dependencies
    if [ ! -d "node_modules" ]; then
        log "INFO" "📦 Installing dependencies with Bun..."
        if ! bun install; then
            log "ERROR" "Gagal install dependencies!"
            cd "$current_dir"
            return 1
        fi
    fi
    
    # Build for production
    log "INFO" "🔨 Building for production with Bun..."
    if ! bun run build; then
        log "ERROR" "❌ Frontend build failed!"
        cd "$current_dir"
        return 1
    fi
    
    # Check if build was successful
    if [ -d "dist" ]; then
        log "INFO" "✅ Frontend build completed successfully!"
        log "INFO" "📁 Build output: frontend/dist/"
        log "INFO" "🎉 Frontend ready for Go embed!"
        cd "$current_dir"
        return 0
    else
        log "ERROR" "❌ Frontend build failed - dist directory not found!"
        cd "$current_dir"
        return 1
    fi
}

# Fungsi untuk build backend dengan embedded frontend
build_backend() {
    log "INFO" "🚀 Building Go Backend..."
    
    # Cek apakah build frontend sudah ada
    if [ ! -d "frontend/dist" ]; then
        log "WARN" "Frontend belum di-build. Building frontend terlebih dahulu..."
        if ! build_frontend; then
            log "ERROR" "Gagal build frontend!"
            return 1
        fi
    fi
    
    # Copy frontend dist to server/static for Go embed
    log "INFO" "📁 Copying frontend dist to server/static..."
    rm -rf server/static/assets server/static/index.html server/static/index.html.fiber.gz server/static/dist server/static/vite.svg
    mkdir -p server/static
    cp -a frontend/dist/. server/static/
    if [ ! -d "server/static/assets" ]; then
        log "ERROR" "Gagal menyalin frontend dist ke server/static!"
        return 1
    fi
    
    # Get the binary name from go.mod or use default
    local binary_name=$(grep "module " go.mod | awk '{print $2}' | xargs basename 2>/dev/null)
    if [ -z "$binary_name" ]; then
        binary_name="loko-backend"
    fi
    
    # Create bin directory if it doesn't exist
    mkdir -p bin
    
    # Build for current platform
    log "INFO" "🔨 Building binary: $binary_name"
    if ! go build -o bin/$binary_name .; then
        log "ERROR" "❌ Backend build failed!"
        return 1
    fi
    
    # Check if build was successful
    if [ -f "bin/$binary_name" ]; then
        log "INFO" "✅ Backend build completed successfully!"
        log "INFO" "📁 Binary location: bin/$binary_name"
        log "INFO" "🏃 Run with: ./bin/$binary_name"
        log "INFO" "🎉 Backend ready to run!"
        return 0
    else
        log "ERROR" "❌ Backend build failed - binary not found!"
        return 1
    fi
}

# Fungsi untuk build full stack (frontend + backend)
build_fullstack() {
    log "INFO" "🚀 Building Full Stack Application..."
    
    # Step 1: Build frontend
    log "INFO" "📦 Step 1: Building Frontend..."
    if ! build_frontend; then
        log "ERROR" "❌ Frontend build failed!"
        return 1
    fi
    
    # Step 2: Build backend with embedded frontend
    log "INFO" "🔧 Step 2: Building Backend..."
    if ! build_backend; then
        log "ERROR" "❌ Backend build failed!"
        return 1
    fi
    
    # Get binary name for final message
    local binary_name=$(grep "module " go.mod | awk '{print $2}' | xargs basename 2>/dev/null)
    if [ -z "$binary_name" ]; then
        binary_name="loko-backend"
    fi
    
    log "INFO" "🎉 Full stack build completed successfully!"
    log "INFO" "🏃 Run the application with: ./bin/$binary_name"
    return 0
}

# Fungsi untuk build native (sederhana) - frontend + backend
build_native() {
    log "INFO" "🚀 Building Native Application (Frontend + Backend)..."
    
    # Build frontend dengan Bun
    if ! build_frontend; then
        log "ERROR" "❌ Frontend build failed!"
        return 1
    fi
    
    # Copy frontend dist to backend static
    log "INFO" "📁 Copying frontend dist to backend static..."
    if [ -d "frontend/dist" ]; then
        # Create static directory if it doesn't exist
        mkdir -p server/static
        
        # Remove old dist if exists
        if [ -d "server/static/dist" ]; then
            rm -rf server/static/dist
        fi
        
        # Copy new dist
        cp -r frontend/dist server/static/
        log "INFO" "✅ Frontend dist copied to server/static/dist"
    else
        log "ERROR" "❌ Frontend dist directory not found!"
        return 1
    fi
    
    # Build backend dengan Go embed
    if ! build_backend; then
        log "ERROR" "❌ Backend build failed!"
        return 1
    fi
    
    log "INFO" "🎉 Native build completed successfully!"
    log "INFO" "📁 Binary: bin/${BINARY_NAME}"
    log "INFO" "🚀 Ready to run: ./bin/${BINARY_NAME}"
    return 0
}

# Fungsi untuk build dengan Docker Compose
build_docker() {
    log "INFO" "Memulai proses build dengan Docker Compose..."
    
    # Cek apakah docker-compose.yaml ada
    if [ ! -f "infrastructure/docker/docker-compose.yaml" ]; then
        log "ERROR" "File docker-compose.yaml tidak ditemukan!"
        return 1
    fi
    
    # Cek apakah Docker dan Docker Compose terinstall
    if ! command -v docker &> /dev/null; then
        log "ERROR" "Docker tidak terinstall!"
        return 1
    fi
    
    if ! command -v docker-compose -f infrastructure/docker/docker-compose.yaml &> /dev/null; then
        log "ERROR" "Docker Compose tidak terinstall!"
        return 1
    fi
    
    # Build dengan Docker Compose
    log "INFO" "Building Docker image..."
    if docker-compose -f infrastructure/docker/docker-compose.yaml build; then
        log "INFO" "Docker build berhasil!"
        return 0
    else
        log "ERROR" "Docker build gagal!"
        return 1
    fi
}

# Fungsi untuk rebuild dengan Docker Compose
rebuild() {
    log "INFO" "Memulai proses rebuild dengan Docker Compose..."
    
    # Stop container jika sedang berjalan
    log "INFO" "Menghentikan container yang sedang berjalan..."
    docker-compose -f infrastructure/docker/docker-compose.yaml down 2>/dev/null || true
    
    # Hapus image lama
    log "INFO" "Menghapus image lama..."
    docker-compose -f infrastructure/docker/docker-compose.yaml down --rmi all 2>/dev/null || true
    
    # Build ulang
    log "INFO" "Building ulang Docker image..."
    if docker-compose -f infrastructure/docker/docker-compose.yaml build --no-cache; then
        log "INFO" "Rebuild berhasil!"
        return 0
    else
        log "ERROR" "Rebuild gagal!"
        return 1
    fi
}

# Fungsi untuk build dengan optimasi
build_optimized() {
    log "INFO" "Building dengan optimasi..."
    
    local ldflags="-s -w"
    local build_time=$(date -u '+%Y-%m-%d_%H:%M:%S')
    local git_commit=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    
    ldflags="$ldflags -X main.BuildTime=$build_time -X main.GitCommit=$git_commit"
    
    if go build -ldflags="$ldflags" -o "$BINARY_NAME" .; then
        log "INFO" "Build optimized berhasil!"
        log "INFO" "Build time: $build_time"
        log "INFO" "Git commit: $git_commit"
        return 0
    else
        log "ERROR" "Build optimized gagal!"
        return 1
    fi
}

# Fungsi untuk generate Swagger docs
generate_docs() {
    log "INFO" "Generating Swagger documentation..."
    
    if command -v swag &> /dev/null; then
        if swag init; then
            log "INFO" "Swagger docs berhasil di-generate!"
        else
            log "ERROR" "Gagal generate Swagger docs!"
            return 1
        fi
    else
        log "WARN" "Swag tidak terinstall, skip generate docs"
    fi
}

# =============================================================================
# Run Functions
# =============================================================================

# Fungsi untuk menjalankan aplikasi dalam mode development
run_dev() {
    log "INFO" "Menjalankan aplikasi dalam mode development..."
    
    # Step 1: Cleanup semua build native yang ada
    log "INFO" "🧹 Step 1: Membersihkan semua build native yang ada..."
    
    # Hapus binary lama
    if [ -f "$BINARY_NAME" ]; then
        rm -f "$BINARY_NAME"
        log "INFO" "Binary lama dihapus: $BINARY_NAME"
    fi
    
    # Hapus binary di bin directory
    if [ -d "bin" ]; then
        rm -rf bin/*
        log "INFO" "Direktori bin dibersihkan"
    fi
    
    # Bersihkan frontend dist
    if [ -d "frontend/dist" ]; then
        rm -rf frontend/dist
        log "INFO" "Frontend dist dihapus"
    fi
    
    # Bersihkan server static lama
    log "INFO" "Server static dist dan file lama dihapus"
    rm -rf server/static/assets server/static/index.html server/static/index.html.fiber.gz server/static/dist server/static/vite.svg
    
    # Step 2: Kill proses di port yang mungkin konflik
    log "INFO" "🔧 Step 2: Membersihkan port yang mungkin konflik..."
    kill_ports
    
    # Step 3: Cleanup file temporary dan PID lama
    log "INFO" "🧹 Step 3: Membersihkan file temporary..."
    # Hapus PID file lama jika ada
    if [ -f "$PID_FILE" ]; then
        rm -f "$PID_FILE"
        log "INFO" "PID file lama dihapus"
    fi
    
    # Bersihkan temp directory
    if [ -d "$TEMP_DIR" ]; then
        rm -rf "$TEMP_DIR"/*
        log "INFO" "Direktori temp dibersihkan"
    fi
    
    # Bersihkan log lama untuk development yang fresh
    if [ -f "$LOG_FILE" ]; then
        > "$LOG_FILE"  # Kosongkan file log
        log "INFO" "Log file direset untuk development session baru"
    fi
    
    # Step 4: Build frontend untuk development
    log "INFO" "🔨 Step 4: Building frontend untuk development..."
    if ! build_frontend; then
        log "WARN" "Frontend build gagal, membuat direktori dist kosong untuk development..."
        mkdir -p frontend/dist
        echo '<!DOCTYPE html><html><head><title>Development Mode</title></head><body><h1>Development Mode - Frontend belum ready</h1></body></html>' > frontend/dist/index.html
    fi
    
    # Copy frontend dist ke server static untuk embed
    log "INFO" "📁 Copying frontend dist ke server/static..."
    mkdir -p server/static
    cp -a frontend/dist/. server/static/
    
    # Step 5: Setup environment
    log "INFO" "⚙️  Step 5: Setup environment..."
    if [ -f ".env" ]; then
        log "INFO" "Loading environment dari .env"
        set -a  # automatically export all variables
        source <(cat .env | grep -v '^#' | grep -v '^$' | grep '=')
        set +a  # disable automatic export
    else
        log "WARN" "File .env tidak ditemukan, menggunakan .env.example"
        if [ -f ".env.example" ]; then
            cp .env.example .env
            log "INFO" "File .env dibuat dari .env.example"
        fi
    fi
    
    # Step 6: Setup signal handler untuk Ctrl+C
    log "INFO" "⚙️  Step 6: Setup signal handler..."
    
    # Fungsi untuk cleanup saat Ctrl+C
    cleanup_on_exit() {
        log "INFO" ""
        log "INFO" "🛑 Menerima signal interrupt (Ctrl+C)..."
        log "INFO" "🧹 Membersihkan proses development server..."
        
        if [ -f "$PID_FILE" ]; then
            local pid=$(cat "$PID_FILE")
            if ps -p "$pid" > /dev/null 2>&1; then
                log "INFO" "Menghentikan development server dengan PID: $pid"
                kill -TERM "$pid" 2>/dev/null
                sleep 2
                
                # Cek apakah masih berjalan
                if ps -p "$pid" > /dev/null 2>&1; then
                    log "WARN" "Proses masih berjalan, menggunakan SIGKILL..."
                    kill -KILL "$pid" 2>/dev/null
                fi
            fi
            rm -f "$PID_FILE"
        fi
        
        log "INFO" "✅ Development server berhasil dihentikan"
        log "INFO" "👋 Terima kasih telah menggunakan Loko Backend!"
        exit 0
    }
    
    # Set trap untuk menangkap SIGINT (Ctrl+C) dan SIGTERM
    trap cleanup_on_exit SIGINT SIGTERM
    
    # Step 7: Jalankan development server
    log "INFO" "🚀 Step 7: Starting development server..."
    log "INFO" "Development server akan mendeteksi perubahan file secara otomatis"
    log "INFO" "🛑 Tekan Ctrl+C untuk menghentikan server dengan aman"
    
    go run . 2>&1 | tee "$LOG_FILE" &
    local pid=$!
    echo $pid > "$PID_FILE"
    
    log "INFO" "✅ Development server berjalan dengan PID: $pid"
    log "INFO" "📁 Log file: $LOG_FILE"
    log "INFO" "🔄 Server akan restart otomatis saat ada perubahan kode"
    
    # Wait untuk proses development server
    wait $pid
}

# Fungsi untuk menjalankan aplikasi dari binary
run_prod() {
    log "INFO" "Menjalankan aplikasi dalam mode production..."
    
    # Cek apakah sudah berjalan
    if is_running; then
        log "WARN" "Aplikasi sudah berjalan! PID: $(cat $PID_FILE)"
        return 1
    fi
    
    # Cek apakah binary ada
    if [ ! -f "$BINARY_NAME" ]; then
        log "ERROR" "Binary $BINARY_NAME tidak ditemukan! Jalankan 'build' terlebih dahulu."
        return 1
    fi
    
    # Setup environment
    if [ -f ".env" ]; then
        export $(cat .env | grep -v '^#' | xargs)
    fi
    
    # Jalankan binary
    log "INFO" "Starting production server..."
    nohup "./$BINARY_NAME" > "$LOG_FILE" 2> "$ERROR_LOG" &
    local pid=$!
    echo $pid > "$PID_FILE"
    
    log "INFO" "Aplikasi berjalan dengan PID: $pid"
    log "INFO" "Log file: $LOG_FILE"
    log "INFO" "Error log: $ERROR_LOG"
}

# Fungsi untuk menjalankan dengan hot reload
run_watch() {
    log "INFO" "Menjalankan dengan hot reload..."
    
    # Cek apakah air terinstall
    if ! command -v air &> /dev/null; then
        log "WARN" "Air tidak terinstall. Install dengan: go install github.com/cosmtrek/air@latest"
        log "INFO" "Menggunakan mode development biasa..."
        run_dev
        return
    fi
    
    # Jalankan dengan air
    air
}

# Fungsi untuk menjalankan dengan Docker Compose
run_docker() {
    log "INFO" "Menjalankan aplikasi dengan Docker Compose..."
    
    # Cek apakah docker-compose.yaml ada
    if [ ! -f "infrastructure/docker/docker-compose.yaml" ]; then
        log "ERROR" "File docker-compose.yaml tidak ditemukan!"
        return 1
    fi
    
    # Cek apakah Docker dan Docker Compose terinstall
    if ! command -v docker &> /dev/null; then
        log "ERROR" "Docker tidak terinstall!"
        return 1
    fi
    
    if ! command -v docker-compose -f infrastructure/docker/docker-compose.yaml &> /dev/null; then
        log "ERROR" "Docker Compose tidak terinstall!"
        return 1
    fi
    
    # Jalankan dengan Docker Compose
    log "INFO" "Starting Docker containers..."
    if docker-compose -f infrastructure/docker/docker-compose.yaml up -d; then
        log "INFO" "Docker containers berhasil dijalankan!"
        
        # Tampilkan status container
        log "INFO" "Status containers:"
        docker-compose -f infrastructure/docker/docker-compose.yaml ps
        
        return 0
    else
        log "ERROR" "Gagal menjalankan Docker containers!"
        return 1
    fi
}

# Fungsi untuk menjalankan Docker Compose dengan build
run_docker_build() {
    log "INFO" "Menjalankan aplikasi dengan Docker Compose (build + run)..."
    
    # Build terlebih dahulu
    if build_docker; then
        log "INFO" "Build berhasil, menjalankan containers..."
        run_docker
    else
        log "ERROR" "Build gagal, tidak dapat menjalankan containers!"
        return 1
    fi
}

# =============================================================================
# Control Functions
# =============================================================================

# Fungsi untuk menghentikan aplikasi (native)
stop() {
    log "INFO" "Menghentikan aplikasi native..."
    
    if is_running; then
        local pid=$(cat "$PID_FILE")
        log "INFO" "Menghentikan proses dengan PID: $pid"
        
        # Kirim SIGTERM terlebih dahulu
        kill -TERM "$pid" 2>/dev/null
        
        # Tunggu beberapa detik
        sleep 3
        
        # Cek apakah masih berjalan
        if ps -p "$pid" > /dev/null 2>&1; then
            log "WARN" "Proses masih berjalan, menggunakan SIGKILL..."
            kill -KILL "$pid" 2>/dev/null
        fi
        
        rm -f "$PID_FILE"
        log "INFO" "Aplikasi berhasil dihentikan"
    else
        log "WARN" "Aplikasi tidak sedang berjalan"
    fi
}

# Fungsi untuk menghentikan Docker containers
stop_docker() {
    log "INFO" "Menghentikan Docker containers..."
    
    # Cek apakah ada container yang berjalan
    if docker-compose -f infrastructure/docker/docker-compose.yaml ps -q | grep -q .; then
        log "INFO" "Menghentikan containers..."
        if docker-compose -f infrastructure/docker/docker-compose.yaml down; then
            log "INFO" "Docker containers berhasil dihentikan"
        else
            log "ERROR" "Gagal menghentikan Docker containers"
            return 1
        fi
    else
        log "WARN" "Tidak ada Docker containers yang berjalan"
    fi
}

# Fungsi untuk kill proses di port tertentu
kill_ports() {
    log "INFO" "Menghentikan proses di port yang digunakan..."
    
    # Port yang umum digunakan oleh aplikasi Loko
    local ports=(1234)
    
    for port in "${ports[@]}"; do
        log "INFO" "Checking port $port..."
        
        # Cari proses yang menggunakan port
        local pids=$(lsof -ti :$port 2>/dev/null)
        
        if [ -n "$pids" ]; then
            log "INFO" "Menghentikan proses di port $port: $pids"
            
            # Kill dengan SIGTERM terlebih dahulu
            echo "$pids" | xargs -r kill -TERM 2>/dev/null
            sleep 2
            
            # Cek apakah masih ada yang berjalan
            local remaining_pids=$(lsof -ti :$port 2>/dev/null)
            if [ -n "$remaining_pids" ]; then
                log "WARN" "Proses masih berjalan di port $port, menggunakan SIGKILL..."
                echo "$remaining_pids" | xargs -r kill -KILL 2>/dev/null
            fi
            
            log "INFO" "Port $port berhasil dibersihkan"
        else
            log "DEBUG" "Port $port tidak digunakan"
        fi
    done
}

# Fungsi untuk cleanup lengkap
cleanup_all() {
    log "INFO" "Melakukan cleanup lengkap..."
    
    # Hapus PID file
    if [ -f "$PID_FILE" ]; then
        rm -f "$PID_FILE"
        log "INFO" "PID file dihapus"
    fi
    
    # Bersihkan temp directory
    if [ -d "$TEMP_DIR" ]; then
        rm -rf "$TEMP_DIR"/*
        log "INFO" "Direktori temp dibersihkan"
    fi
    
    # Hapus binary lama
    if [ -f "$BINARY_NAME" ]; then
        rm -f "$BINARY_NAME"
        log "INFO" "Binary lama dihapus"
    fi
    
    # Hapus binary di bin directory
    if [ -d "bin" ]; then
        rm -rf bin/*
        log "INFO" "Direktori bin dibersihkan"
    fi
    
    # Bersihkan frontend dist
    if [ -d "frontend/dist" ]; then
        rm -rf frontend/dist
        log "INFO" "Frontend dist dihapus"
    fi
    
    # Bersihkan server static
    if [ -d "server/static/dist" ]; then
        rm -rf server/static/dist
        log "INFO" "Server static dist dihapus"
    fi
    
    # Bersihkan node_modules jika ada (untuk fresh install)
    if [ -d "frontend/node_modules" ]; then
        log "INFO" "Menghapus node_modules untuk fresh install..."
        rm -rf frontend/node_modules
    fi
    
    log "INFO" "Cleanup lengkap selesai"
}

# Fungsi untuk rebuild semua komponen
rebuild_all() {
    log "INFO" "🚀 Memulai rebuild semua komponen..."
    
    # Step 1: Install/update frontend dependencies
    log "INFO" "📦 Step 1: Installing frontend dependencies..."
    if [ -d "frontend" ]; then
        cd frontend
        
        # Cek apakah Bun terinstall (required)
        if command -v bun &> /dev/null; then
            log "INFO" "Installing dependencies dengan Bun..."
            if ! bun install; then
                log "ERROR" "❌ Gagal install dependencies dengan Bun!"
                cd ..
                return 1
            fi
        else
            log "ERROR" "❌ Bun tidak terinstall! Install dengan: curl -fsSL https://bun.sh/install | bash"
            cd ..
            return 1
        fi
        
        cd ..
        log "INFO" "✅ Frontend dependencies berhasil diinstall"
    fi
    
    # Step 2: Build frontend
    log "INFO" "🔨 Step 2: Building frontend..."
    if ! build_frontend; then
        log "ERROR" "❌ Frontend build gagal!"
        return 1
    fi
    
    # Step 3: Build backend
    log "INFO" "🔧 Step 3: Building backend..."
    if ! build_backend; then
        log "ERROR" "❌ Backend build gagal!"
        return 1
    fi
    
    # Step 4: Generate docs jika swag tersedia
    log "INFO" "📚 Step 4: Generating documentation..."
    generate_docs
    
    log "INFO" "🎉 Rebuild semua komponen berhasil!"
    log "INFO" "🚀 Aplikasi siap dijalankan dengan: ./manage.sh run-prod"
    
    return 0
}

# =============================================================================
# Simple Deploy/Destroy Functions
# =============================================================================

# Fungsi deploy: Build dan jalankan production dengan Docker
deploy() {
    log "INFO" "🚀 Starting production deployment with Docker..."
    
    # Step 1: Stop existing containers
    log "INFO" "📦 Step 1: Stopping existing containers..."
    docker-compose -f infrastructure/docker/docker-compose.yaml down 2>/dev/null || true
    
    # Step 2: Build Docker images
    log "INFO" "🔨 Step 2: Building Docker images..."
    if ! docker-compose -f infrastructure/docker/docker-compose.yaml build --no-cache; then
        log "ERROR" "❌ Docker build failed!"
        return 1
    fi
    
    # Step 3: Start containers
    log "INFO" "🚀 Step 3: Starting containers..."
    if ! docker-compose -f infrastructure/docker/docker-compose.yaml up -d; then
        log "ERROR" "❌ Failed to start containers!"
        return 1
    fi
    
    # Step 4: Show status
    log "INFO" "📊 Step 4: Deployment status..."
    docker-compose -f infrastructure/docker/docker-compose.yaml ps
    
    log "INFO" "✅ Deployment completed successfully!"
    log "INFO" "📍 Application URL: http://localhost:2000"
    log "INFO" "📍 PostgreSQL: localhost:5432"
    log "INFO" "📋 View logs: ./manage.sh logs-docker"
    log "INFO" "🛑 Destroy: ./manage.sh destroy"
    
    return 0
}

# Fungsi destroy: Stop dan hapus semua containers, networks, dan volumes
destroy() {
    log "WARN" "🗑️  Destroying Docker deployment..."
    log "INFO" "Note: Database volumes will be preserved"
    
    # Confirmation
    read -p "Stop all containers? (yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        log "INFO" "Destroy cancelled."
        return 0
    fi
    
    # Step 1: Stop containers (keep volumes!)
    log "INFO" "🛑 Step 1: Stopping containers..."
    docker-compose -f infrastructure/docker/docker-compose.yaml down --remove-orphans
    
    # Step 2: Clean up dangling images
    log "INFO" "🧹 Step 2: Cleaning up Docker images..."
    docker image prune -f
    
    log "INFO" "✅ Deployment stopped successfully!"
    log "INFO" "💾 Database volumes preserved"
    log "INFO" "🚀 Deploy again: ./manage.sh deploy"
    
    return 0
}

# Fungsi untuk menghentikan semua (native + docker + ports + rebuild)
stop_all() {
    log "INFO" "🛑 Menghentikan semua aplikasi dan melakukan rebuild..."
    
    # Step 1: Stop native application
    log "INFO" "Step 1: Menghentikan aplikasi native..."
    stop
    
    # Step 2: Stop Docker containers
    log "INFO" "Step 2: Menghentikan Docker containers..."
    stop_docker
    
    # Step 3: Kill processes on ports
    log "INFO" "Step 3: Menghentikan proses di port..."
    kill_ports
    
    # Step 4: Cleanup all files
    log "INFO" "Step 4: Melakukan cleanup..."
    cleanup_all
    
    # Step 5: Rebuild everything
    log "INFO" "Step 5: Rebuild semua komponen..."
    if rebuild_all; then
        log "INFO" "🎉 Stop-all dan rebuild berhasil!"
        log "INFO" "🚀 Aplikasi siap dijalankan dengan: ./manage.sh run-prod"
        return 0
    else
        log "ERROR" "❌ Rebuild gagal!"
        return 1
    fi
}

# Fungsi untuk restart aplikasi (native)
restart() {
    log "INFO" "Restarting aplikasi native dengan build..."
    
    # Step 1: Stop aplikasi yang sedang berjalan
    log "INFO" "🛑 Step 1: Menghentikan aplikasi yang sedang berjalan..."
    stop
    sleep 2
    
    # Step 2: Build frontend
    log "INFO" "🔨 Step 2: Building frontend..."
    if ! build_frontend; then
        log "ERROR" "❌ Frontend build gagal! Restart dibatalkan."
        return 1
    fi
    
    # Step 3: Copy frontend dist ke server/static
    log "INFO" "📁 Step 3: Copying frontend dist ke server/static..."
    if [ -d "frontend/dist" ]; then
        # Create static directory if it doesn't exist
        mkdir -p server/static
        
        # Remove old dist if exists
        if [ -d "server/static/dist" ]; then
            rm -rf server/static/dist
        fi
        
        # Copy new dist
        cp -r frontend/dist server/static/
        log "INFO" "✅ Frontend dist berhasil disalin ke server/static/dist"
    else
        log "ERROR" "❌ Frontend dist directory tidak ditemukan!"
        return 1
    fi
    
    # Step 4: Build backend
    log "INFO" "🔧 Step 4: Building backend..."
    if ! build; then
        log "ERROR" "❌ Backend build gagal! Restart dibatalkan."
        return 1
    fi
    
    # Step 5: Jalankan aplikasi
    log "INFO" "🚀 Step 5: Starting aplikasi..."
    run_prod
    
    if [ $? -eq 0 ]; then
        log "INFO" "🎉 Restart dengan build berhasil!"
        log "INFO" "📊 Gunakan './manage.sh status' untuk cek status aplikasi"
    else
        log "ERROR" "❌ Gagal menjalankan aplikasi setelah build!"
        return 1
    fi
}

# Fungsi untuk restart Docker containers
restart_docker() {
    log "INFO" "Restarting Docker containers..."
    stop_docker
    sleep 2
    run_docker
}

# Fungsi untuk restart semua
restart_all() {
    log "INFO" "Restarting semua aplikasi..."
    stop_all
    sleep 2
    
    # Tanya user mau jalankan yang mana
    echo -e "${YELLOW}Pilih mode untuk restart:${NC}"
    echo "1) Native (go run)"
    echo "2) Docker Compose"
    echo "3) Keduanya"
    read -p "Pilihan (1-3): " choice
    
    case $choice in
        1)
            run_prod
            ;;
        2)
            run_docker
            ;;
        3)
            run_prod &
            run_docker
            ;;
        *)
            log "WARN" "Pilihan tidak valid, menjalankan mode native"
            run_prod
            ;;
    esac
}

# Fungsi untuk mengecek status aplikasi
status() {
    echo -e "${CYAN}=== STATUS APLIKASI NATIVE ===${NC}"
    
    if is_running; then
        local pid=$(cat "$PID_FILE")
        echo -e "${GREEN}Status: RUNNING${NC}"
        echo -e "PID: $pid"
        echo -e "Uptime: $(ps -o etime= -p $pid | tr -d ' ')"
        echo -e "Memory: $(ps -o rss= -p $pid | tr -d ' ') KB"
    else
        echo -e "${RED}Status: STOPPED${NC}"
    fi
    
    echo ""
    echo -e "${CYAN}=== STATUS DOCKER CONTAINERS ===${NC}"
    
    if command -v docker-compose -f infrastructure/docker/docker-compose.yaml &> /dev/null; then
        if [ -f "infrastructure/docker/docker-compose.yaml" ]; then
            # Cek status containers
            local containers=$(docker-compose -f infrastructure/docker/docker-compose.yaml ps -q 2>/dev/null)
            if [ -n "$containers" ]; then
                echo -e "${GREEN}Docker Compose: AVAILABLE${NC}"
                docker-compose -f infrastructure/docker/docker-compose.yaml ps
            else
                echo -e "${YELLOW}Docker Compose: NO RUNNING CONTAINERS${NC}"
            fi
        else
            echo -e "${RED}Docker Compose: docker-compose.yaml NOT FOUND${NC}"
        fi
    else
        echo -e "${RED}Docker Compose: NOT INSTALLED${NC}"
    fi
    
    echo ""
    echo -e "${CYAN}=== INFORMASI SISTEM ===${NC}"
    echo -e "Go version: $(go version | awk '{print $3}')"
    echo -e "OS: $(uname -s)"
    echo -e "Architecture: $(uname -m)"
    
    if [ -f "$BINARY_NAME" ]; then
        echo -e "Binary: ${GREEN}EXISTS${NC} ($(ls -lh $BINARY_NAME | awk '{print $5}'))"
    else
        echo -e "Binary: ${RED}NOT FOUND${NC}"
    fi
    
    # Cek Docker images
    if command -v docker &> /dev/null; then
        echo -e "Docker: ${GREEN}INSTALLED${NC}"
        local images=$(docker images | grep loko-backend | wc -l | tr -d ' ')
        echo -e "Docker Images: $images"
    else
        echo -e "Docker: ${RED}NOT INSTALLED${NC}"
    fi
}

# =============================================================================
# Maintenance Functions
# =============================================================================

# Fungsi untuk membersihkan file temporary
clean() {
    log "INFO" "Membersihkan file temporary..."
    
    # Hentikan aplikasi jika berjalan
    if is_running; then
        log "WARN" "Menghentikan aplikasi terlebih dahulu..."
        stop
    fi
    
    # Hapus binary
    if [ -f "$BINARY_NAME" ]; then
        rm -f "$BINARY_NAME"
        log "INFO" "Binary $BINARY_NAME dihapus"
    fi
    
    # Bersihkan temp directory
    if [ -d "$TEMP_DIR" ]; then
        rm -rf "$TEMP_DIR"/*
        log "INFO" "Direktori temp dibersihkan"
    fi
    
    # Bersihkan log lama (lebih dari 7 hari)
    if [ -d "$LOG_DIR" ]; then
        find "$LOG_DIR" -name "*.log" -mtime +7 -delete 2>/dev/null
        log "INFO" "Log lama (>7 hari) dihapus"
    fi
    
    # Hapus PID file
    rm -f "$PID_FILE"
    
    log "INFO" "Cleanup selesai"
}

# Fungsi untuk install dependencies
install() {
    log "INFO" "Installing dependencies..."
    
    # Go mod tidy
    if go mod tidy; then
        log "INFO" "Go modules berhasil di-update"
    else
        log "ERROR" "Gagal update Go modules"
        return 1
    fi
    
    # Download dependencies
    if go mod download; then
        log "INFO" "Dependencies berhasil di-download"
    else
        log "ERROR" "Gagal download dependencies"
        return 1
    fi
    
    # Install development tools (optional)
    log "INFO" "Installing development tools..."
    
    # Air untuk hot reload
    if ! command -v air &> /dev/null; then
        log "INFO" "Installing air..."
        go install github.com/cosmtrek/air@latest
    fi
    
    # Swag untuk Swagger
    if ! command -v swag &> /dev/null; then
        log "INFO" "Installing swag..."
        go install github.com/swaggo/swag/cmd/swag@latest
    fi
    
    log "INFO" "Installation selesai"
}

# =============================================================================
# Log Functions
# =============================================================================

# Fungsi untuk melihat log
logs() {
    local lines=${1:-50}
    
    echo -e "${CYAN}=== LOGS (Last $lines lines) ===${NC}"
    
    if [ -f "$LOG_FILE" ]; then
        tail -n "$lines" "$LOG_FILE"
    else
        log "WARN" "Log file tidak ditemukan: $LOG_FILE"
    fi
}

# Fungsi untuk melihat error log
error_logs() {
    local lines=${1:-50}
    
    echo -e "${RED}=== ERROR LOGS (Last $lines lines) ===${NC}"
    
    if [ -f "$ERROR_LOG" ]; then
        tail -n "$lines" "$ERROR_LOG"
    else
        log "WARN" "Error log file tidak ditemukan: $ERROR_LOG"
    fi
}

# Fungsi untuk follow log real-time
follow_logs() {
    echo -e "${CYAN}=== FOLLOWING LOGS (Press Ctrl+C to stop) ===${NC}"
    
    if [ -f "$LOG_FILE" ]; then
        tail -f "$LOG_FILE"
    else
        log "WARN" "Log file tidak ditemukan: $LOG_FILE"
    fi
}

# Fungsi untuk melihat Docker logs
logs_docker() {
    local service=${1:-"loko-backend"}
    local lines=${2:-50}
    
    echo -e "${CYAN}=== DOCKER LOGS (Last $lines lines) ===${NC}"
    
    if command -v docker-compose -f infrastructure/docker/docker-compose.yaml &> /dev/null; then
        if docker-compose -f infrastructure/docker/docker-compose.yaml ps -q "$service" > /dev/null 2>&1; then
            docker-compose -f infrastructure/docker/docker-compose.yaml logs --tail="$lines" "$service"
        else
            log "WARN" "Service $service tidak ditemukan atau tidak berjalan"
        fi
    else
        log "ERROR" "Docker Compose tidak terinstall"
    fi
}

# Fungsi untuk follow Docker logs
follow_logs_docker() {
    local service=${1:-"loko-backend"}
    
    echo -e "${CYAN}=== FOLLOWING DOCKER LOGS (Press Ctrl+C to stop) ===${NC}"
    
    if command -v docker-compose -f infrastructure/docker/docker-compose.yaml &> /dev/null; then
        if docker-compose -f infrastructure/docker/docker-compose.yaml ps -q "$service" > /dev/null 2>&1; then
            docker-compose -f infrastructure/docker/docker-compose.yaml logs -f "$service"
        else
            log "WARN" "Service $service tidak ditemukan atau tidak berjalan"
        fi
    else
        log "ERROR" "Docker Compose tidak terinstall"
    fi
}

# =============================================================================
# Testing Functions
# =============================================================================

# Fungsi untuk menjalankan test
test() {
    log "INFO" "Menjalankan tests..."
    
    # Test dengan coverage
    if go test -v -cover ./...; then
        log "INFO" "Semua tests berhasil!"
    else
        log "ERROR" "Ada tests yang gagal!"
        return 1
    fi
}

# Fungsi untuk test dengan coverage detail
test_coverage() {
    log "INFO" "Menjalankan tests dengan coverage detail..."
    
    local coverage_file="coverage.out"
    
    # Jalankan test dengan coverage
    if go test -coverprofile="$coverage_file" ./...; then
        log "INFO" "Tests berhasil!"
        
        # Tampilkan coverage
        go tool cover -func="$coverage_file"
        
        # Generate HTML coverage report
        go tool cover -html="$coverage_file" -o "coverage.html"
        log "INFO" "Coverage report: coverage.html"
    else
        log "ERROR" "Tests gagal!"
        return 1
    fi
}

# =============================================================================
# Database Functions
# =============================================================================

# Fungsi untuk mengecek koneksi database
check_db() {
    log "INFO" "Mengecek koneksi database..."
    
    # Cek apakah aplikasi berjalan
    if ! is_running; then
        log "ERROR" "Aplikasi tidak berjalan. Start aplikasi terlebih dahulu."
        return 1
    fi
    
    # Cek endpoint health (jika ada)
    local health_url="http://localhost:${SERVER_PORT:-8080}/health"
    
    if command -v curl &> /dev/null; then
        if curl -s "$health_url" > /dev/null; then
            log "INFO" "Database connection OK"
        else
            log "ERROR" "Database connection failed"
        fi
    else
        log "WARN" "curl tidak tersedia, tidak bisa cek database"
    fi
}

# Fungsi untuk membersihkan database
clean_db() {
    log "INFO" "Membersihkan database..."

    # Cek apakah psql tersedia - jika tidak, error
    if ! command -v psql &> /dev/null; then
        log "ERROR" "psql tidak ditemukan! Pastikan PostgreSQL client terinstall."
        return 1
    fi

    # Konfirmasi user (double check untuk safety)
    echo -e "${RED}⚠️  PERINGATAN: Command ini akan MENGHAPUS SEMUA DATA di database loko_db!${NC}"
    echo -e "${RED}⚠️  Schema 'public' akan di drop dan dibuat ulang.${NC}"
    read -p "Apakah Anda yakin ingin melanjutkan? (y/N): " confirm

    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        log "INFO" "Operasi dibatalkan oleh user."
        return 0
    fi

    log "WARN" "Menghapus schema public..."
    
    # Execute SQL command
    # Menggunakan PGPASSWORD="" karena user setup bilang password kosong
    if PGPASSWORD="" psql -U macbookairm2 -d loko_db -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO public;" 2>/tmp/db_clean_err; then
        log "INFO" "✅ Database berhasil dibersihkan (Schema public reset)"
        log "INFO" "Silakan jalankan ulang aplikasi untuk auto-migration."
    else
        log "ERROR" "Gagal membersihkan database!"
        cat /tmp/db_clean_err
        return 1
    fi
}

# =============================================================================
# Environment Functions
# =============================================================================

# Fungsi untuk setup environment
setup_env() {
    log "INFO" "Setting up environment..."
    
    if [ ! -f ".env" ]; then
        if [ -f ".env.example" ]; then
            cp .env.example .env
            log "INFO" "File .env dibuat dari .env.example"
            log "WARN" "Silakan edit .env dan sesuaikan konfigurasi!"
        else
            log "ERROR" "File .env.example tidak ditemukan!"
            return 1
        fi
    else
        log "INFO" "File .env sudah ada"
    fi
    
    # Validasi environment variables yang penting
    validate_env
}

# Fungsi untuk validasi environment
validate_env() {
    log "INFO" "Validating environment variables..."
    
    if [ ! -f ".env" ]; then
        log "ERROR" "File .env tidak ditemukan!"
        return 1
    fi
    
    # Load environment
    source .env
    
    # Cek variabel penting
    local required_vars=("SERVER_PORT" "MONGO_URL" "SECRET_KEY")
    local missing_vars=()
    
    for var in "${required_vars[@]}"; do
        if [ -z "${!var}" ]; then
            missing_vars+=("$var")
        fi
    done
    
    if [ ${#missing_vars[@]} -gt 0 ]; then
        log "ERROR" "Environment variables berikut belum diset:"
        for var in "${missing_vars[@]}"; do
            echo "  - $var"
        done
        return 1
    fi
    
    log "INFO" "Environment validation passed"
}

# Fungsi untuk backup environment
backup_env() {
    log "INFO" "Backing up environment..."
    
    if [ -f ".env" ]; then
        local backup_file=".env.backup.$(date +%Y%m%d_%H%M%S)"
        cp .env "$backup_file"
        log "INFO" "Environment backup: $backup_file"
    else
        log "WARN" "File .env tidak ditemukan, tidak ada yang di-backup"
    fi
}

# =============================================================================
# Monitoring Functions
# =============================================================================

# Fungsi untuk monitoring sistem
monitor() {
    echo -e "${CYAN}=== SYSTEM MONITORING ===${NC}"
    
    # CPU dan Memory usage
    echo -e "${YELLOW}CPU & Memory:${NC}"
    if command -v top &> /dev/null; then
        top -l 1 -n 0 | grep "CPU usage\|PhysMem"
    fi
    
    echo ""
    
    # Disk usage
    echo -e "${YELLOW}Disk Usage:${NC}"
    df -h . | tail -1
    
    echo ""
    
    # Network connections
    echo -e "${YELLOW}Network Connections:${NC}"
    if is_running; then
        local port=${SERVER_PORT:-8080}
        netstat -an | grep ":$port" | head -5
    else
        echo "Aplikasi tidak berjalan"
    fi
    
    echo ""
    
    # Process info
    if is_running; then
        local pid=$(cat "$PID_FILE")
        echo -e "${YELLOW}Process Info:${NC}"
        ps -p "$pid" -o pid,ppid,user,%cpu,%mem,vsz,rss,tty,stat,start,time,command
    fi
}

# Fungsi untuk health check
health_check() {
    log "INFO" "Performing health check..."
    
    local health_status=0
    
    # Cek apakah aplikasi berjalan
    if ! is_running; then
        log "ERROR" "Aplikasi tidak berjalan"
        health_status=1
    else
        log "INFO" "✓ Aplikasi berjalan"
    fi
    
    # Cek koneksi ke port
    local port=${SERVER_PORT:-8080}
    if command -v nc &> /dev/null; then
        if nc -z localhost "$port" 2>/dev/null; then
            log "INFO" "✓ Port $port dapat diakses"
        else
            log "ERROR" "✗ Port $port tidak dapat diakses"
            health_status=1
        fi
    fi
    
    # Cek file log
    if [ -f "$LOG_FILE" ]; then
        local log_size=$(stat -f%z "$LOG_FILE" 2>/dev/null || stat -c%s "$LOG_FILE" 2>/dev/null)
        if [ "$log_size" -gt 0 ]; then
            log "INFO" "✓ Log file aktif ($log_size bytes)"
        else
            log "WARN" "⚠ Log file kosong"
        fi
    else
        log "WARN" "⚠ Log file tidak ditemukan"
    fi
    
    # Cek error dalam log terakhir
    if [ -f "$ERROR_LOG" ]; then
        local recent_errors=$(tail -n 10 "$ERROR_LOG" | grep -c "ERROR" 2>/dev/null || echo 0)
        if [ "$recent_errors" -gt 0 ]; then
            log "WARN" "⚠ Ditemukan $recent_errors error dalam 10 baris terakhir"
        else
            log "INFO" "✓ Tidak ada error terbaru"
        fi
    fi
    
    if [ $health_status -eq 0 ]; then
        log "INFO" "Health check PASSED"
    else
        log "ERROR" "Health check FAILED"
    fi
    
    return $health_status
}

# Fungsi untuk performance metrics
performance() {
    echo -e "${CYAN}=== PERFORMANCE METRICS ===${NC}"
    
    if ! is_running; then
        log "ERROR" "Aplikasi tidak berjalan"
        return 1
    fi
    
    local pid=$(cat "$PID_FILE")
    
    # Memory usage
    echo -e "${YELLOW}Memory Usage:${NC}"
    ps -p "$pid" -o pid,rss,vsz,pmem
    
    # CPU usage
    echo -e "${YELLOW}CPU Usage:${NC}"
    ps -p "$pid" -o pid,pcpu,time
    
    # File descriptors
    echo -e "${YELLOW}File Descriptors:${NC}"
    if [ -d "/proc/$pid/fd" ]; then
        echo "Open FDs: $(ls /proc/$pid/fd | wc -l)"
    fi
    
    # Network connections
    echo -e "${YELLOW}Network Connections:${NC}"
    netstat -an | grep ":${SERVER_PORT:-8080}" | wc -l | xargs echo "Active connections:"
}

# =============================================================================
# Backup Functions
# =============================================================================

# Fungsi untuk backup project
backup() {
    log "INFO" "Creating project backup..."
    
    local backup_dir="backups"
    local timestamp=$(date +%Y%m%d_%H%M%S)
    local backup_name="${APP_NAME}_backup_${timestamp}"
    local backup_path="${backup_dir}/${backup_name}.tar.gz"
    
    # Buat direktori backup
    mkdir -p "$backup_dir"
    
    # Daftar file/direktori yang akan di-backup
    local backup_items=(
        "*.go"
        "go.mod"
        "go.sum"
        ".env.example"
        "server/"
        "docs/"
        "README.md"
        "manage.sh"
    )
    
    # Buat backup
    if tar -czf "$backup_path" "${backup_items[@]}" 2>/dev/null; then
        log "INFO" "Backup berhasil: $backup_path"
        
        # Tampilkan ukuran backup
        local size=$(ls -lh "$backup_path" | awk '{print $5}')
        log "INFO" "Ukuran backup: $size"
    else
        log "ERROR" "Backup gagal!"
        return 1
    fi
}

# Fungsi untuk cleanup backup lama
cleanup_backups() {
    log "INFO" "Cleaning up old backups..."
    
    local backup_dir="backups"
    local keep_days=7
    
    if [ -d "$backup_dir" ]; then
        # Hapus backup lebih dari 7 hari
        find "$backup_dir" -name "*.tar.gz" -mtime +$keep_days -delete 2>/dev/null
        
        # Hitung backup yang tersisa
        local remaining=$(find "$backup_dir" -name "*.tar.gz" | wc -l)
        log "INFO" "Backup tersisa: $remaining file(s)"
    else
        log "INFO" "Direktori backup tidak ditemukan"
    fi
}

# =============================================================================
# Git Functions
# =============================================================================

# Fungsi untuk commit dan push dengan build check
git_push() {
    local message="$1"
    
    if [ -z "$message" ]; then
        log "ERROR" "Commit message diperlukan!"
        echo "Usage: $0 git-push \"commit message\""
        return 1
    fi
    
    log "INFO" "Checking code sebelum commit..."
    
    # Build check
    if ! build; then
        log "ERROR" "Build gagal! Perbaiki error terlebih dahulu."
        return 1
    fi
    
    # Test check
    if ! test; then
        log "ERROR" "Tests gagal! Perbaiki error terlebih dahulu."
        return 1
    fi
    
    log "INFO" "Code check passed, melakukan commit..."
    
    git add .
    git commit -m "$message"
    git pull
    git push
    
    log "INFO" "Git push selesai"
}

# =============================================================================
# Admin Management Functions
# =============================================================================

# Fungsi untuk membuat akun administrator
create_admin() {
    log "INFO" "Membuat akun administrator..."
    
    # Cek apakah aplikasi sedang berjalan
    if ! is_running; then
        log "ERROR" "Aplikasi tidak berjalan. Start aplikasi terlebih dahulu dengan: $0 dev atau $0 prod"
        return 1
    fi
    
    # Input data admin
    echo -e "${CYAN}=== SETUP AKUN ADMINISTRATOR ===${NC}"
    echo ""
    
    read -p "Nama lengkap admin: " admin_name
    if [ -z "$admin_name" ]; then
        log "ERROR" "Nama tidak boleh kosong!"
        return 1
    fi
    
    read -p "Username admin: " admin_username
    if [ -z "$admin_username" ]; then
        log "ERROR" "Username tidak boleh kosong!"
        return 1
    fi
    
    read -p "Email admin: " admin_email
    if [ -z "$admin_email" ]; then
        log "ERROR" "Email tidak boleh kosong!"
        return 1
    fi
    
    # Input password dengan konfirmasi
    while true; do
        read -s -p "Password admin: " admin_password
        echo ""
        if [ -z "$admin_password" ]; then
            log "ERROR" "Password tidak boleh kosong!"
            continue
        fi
        
        read -s -p "Konfirmasi password: " admin_password_confirm
        echo ""
        
        if [ "$admin_password" = "$admin_password_confirm" ]; then
            break
        else
            log "ERROR" "Password tidak cocok! Silakan coba lagi."
        fi
    done
    
    # Buat JSON payload
    local json_payload=$(cat <<EOF
{
    "name": "$admin_name",
    "username": "$admin_username",
    "email": "$admin_email",
    "password": "$admin_password",
    "role_id": "Administrator",
    "is_verify": true,
    "is_active": true
}
EOF
)
    
    # Dapatkan port dari environment atau gunakan default
    local server_port=${SERVER_PORT:-8000}
    local api_url="http://localhost:${server_port}/api/user/v1/setup-admin"
    
    log "INFO" "Mengirim request ke: $api_url"
    
    # Kirim request ke API
    if command -v curl &> /dev/null; then
        local response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d "$json_payload" \
            "$api_url")
        
        local http_code=$(echo "$response" | tail -n1)
        local response_body=$(echo "$response" | head -n -1)
        
        if [ "$http_code" = "200" ] || [ "$http_code" = "201" ]; then
            log "INFO" "✅ Akun administrator berhasil dibuat!"
            echo ""
            echo -e "${GREEN}=== DETAIL AKUN ADMINISTRATOR ===${NC}"
            echo -e "${GREEN}Nama:${NC} $admin_name"
            echo -e "${GREEN}Username:${NC} $admin_username"
            echo -e "${GREEN}Email:${NC} $admin_email"
            echo -e "${GREEN}Role:${NC} Administrator"
            echo ""
            echo -e "${YELLOW}⚠️  Simpan informasi login ini dengan aman!${NC}"
            echo ""
        else
            log "ERROR" "Gagal membuat akun administrator!"
            log "ERROR" "HTTP Code: $http_code"
            log "ERROR" "Response: $response_body"
            
            # Coba alternatif: buat langsung ke database
            log "INFO" "Mencoba membuat admin melalui database langsung..."
            create_admin_direct
        fi
    else
        log "ERROR" "curl tidak tersedia. Mencoba membuat admin melalui database langsung..."
        create_admin_direct
    fi
}

# Fungsi alternatif untuk membuat admin langsung ke database
create_admin_direct() {
    log "INFO" "Membuat admin langsung ke database MongoDB..."
    
    # Cek apakah mongosh atau mongo tersedia
    local mongo_cmd=""
    if command -v mongosh &> /dev/null; then
        mongo_cmd="mongosh"
    elif command -v mongo &> /dev/null; then
        mongo_cmd="mongo"
    else
        log "ERROR" "MongoDB client (mongosh/mongo) tidak tersedia!"
        log "INFO" "Silakan install MongoDB client atau gunakan method lain."
        return 1
    fi
    
    # Load environment variables
    if [ -f ".env" ]; then
        source .env
    fi
    
    local mongo_uri=${MONGO_URI:-"mongodb://localhost:27017"}
    local mongo_db=${MONGO_NAME:-"loko"}
    
    # Generate ObjectID dan timestamp
    local object_id=$(date +%s | sha256sum | cut -c1-24)
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
    
    # Hash password (simple hash untuk demo - di production gunakan bcrypt)
    local hashed_password=$(echo -n "$admin_password" | sha256sum | cut -d' ' -f1)
    
    # MongoDB script
    local mongo_script="
    use $mongo_db;
    db.users.insertOne({
        _id: ObjectId(),
        name: '$admin_name',
        username: '$admin_username',
        email: '$admin_email',
        password: '$hashed_password',
        role_id: 'Administrator',
        is_verify: true,
        is_active: true,
        credits: 0,
        created_at: new Date(),
        updated_at: new Date()
    });
    "
    
    # Eksekusi MongoDB script
    echo "$mongo_script" | $mongo_cmd "$mongo_uri" --quiet
    
    if [ $? -eq 0 ]; then
        log "INFO" "✅ Akun administrator berhasil dibuat langsung ke database!"
        echo ""
        echo -e "${GREEN}=== DETAIL AKUN ADMINISTRATOR ===${NC}"
        echo -e "${GREEN}Nama:${NC} $admin_name"
        echo -e "${GREEN}Username:${NC} $admin_username"
        echo -e "${GREEN}Email:${NC} $admin_email"
        echo -e "${GREEN}Role:${NC} Administrator"
        echo ""
        echo -e "${YELLOW}⚠️  Password telah di-hash dan disimpan dengan aman.${NC}"
        echo -e "${YELLOW}⚠️  Simpan informasi login ini dengan aman!${NC}"
        echo ""
    else
        log "ERROR" "Gagal membuat akun administrator ke database!"
        return 1
    fi
}

# Fungsi untuk list admin accounts
list_admins() {
    log "INFO" "Menampilkan daftar administrator..."
    
    # Load environment variables
    if [ -f ".env" ]; then
        source .env
    fi
    
    local mongo_uri=${MONGO_URI:-"mongodb://localhost:27017"}
    local mongo_db=${MONGO_NAME:-"loko"}
    
    # Cek apakah mongosh atau mongo tersedia
    local mongo_cmd=""
    if command -v mongosh &> /dev/null; then
        mongo_cmd="mongosh"
    elif command -v mongo &> /dev/null; then
        mongo_cmd="mongo"
    else
        log "ERROR" "MongoDB client (mongosh/mongo) tidak tersedia!"
        return 1
    fi
    
    # MongoDB script untuk list admins
    local mongo_script="
    use $mongo_db;
    db.users.find({role_id: 'Administrator'}, {password: 0}).pretty();
    "
    
    echo -e "${CYAN}=== DAFTAR ADMINISTRATOR ===${NC}"
    echo "$mongo_script" | $mongo_cmd "$mongo_uri" --quiet
}

# Fungsi untuk membuat superadmin (alias untuk create_admin dengan label yang lebih jelas)
create_superadmin() {
    log "INFO" "Membuat akun Super Administrator..."
    
    # Cek apakah aplikasi sedang berjalan
    if ! is_running; then
        log "ERROR" "Aplikasi tidak berjalan. Start aplikasi terlebih dahulu dengan: $0 dev atau $0 prod"
        return 1
    fi
    
    # Input data superadmin
    echo -e "${CYAN}=== SETUP AKUN SUPER ADMINISTRATOR ===${NC}"
    echo -e "${YELLOW}⚠️  Super Administrator memiliki akses penuh ke sistem!${NC}"
    echo ""
    
    read -p "Nama lengkap Super Admin: " admin_name
    if [ -z "$admin_name" ]; then
        log "ERROR" "Nama tidak boleh kosong!"
        return 1
    fi
    
    read -p "Username Super Admin: " admin_username
    if [ -z "$admin_username" ]; then
        log "ERROR" "Username tidak boleh kosong!"
        return 1
    fi
    
    read -p "Email Super Admin: " admin_email
    if [ -z "$admin_email" ]; then
        log "ERROR" "Email tidak boleh kosong!"
        return 1
    fi
    
    # Input password dengan konfirmasi
    while true; do
        read -s -p "Password Super Admin: " admin_password
        echo ""
        if [ -z "$admin_password" ]; then
            log "ERROR" "Password tidak boleh kosong!"
            continue
        fi
        
        read -s -p "Konfirmasi password: " admin_password_confirm
        echo ""
        
        if [ "$admin_password" = "$admin_password_confirm" ]; then
            break
        else
            log "ERROR" "Password tidak cocok! Silakan coba lagi."
        fi
    done
    
    # Buat JSON payload
    local json_payload=$(cat <<EOF
{
    "name": "$admin_name",
    "username": "$admin_username",
    "email": "$admin_email",
    "password": "$admin_password",
    "role_id": "Administrator",
    "is_verify": true,
    "is_active": true
}
EOF
)
    
    # Dapatkan port dari environment atau gunakan default
    local server_port=${SERVER_PORT:-8000}
    local api_url="http://localhost:${server_port}/api/user/v1/setup-admin"
    
    log "INFO" "Mengirim request ke: $api_url"
    
    # Kirim request ke API
    if command -v curl &> /dev/null; then
        local response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d "$json_payload" \
            "$api_url")
        
        local http_code=$(echo "$response" | tail -n1)
        local response_body=$(echo "$response" | head -n -1)
        
        if [ "$http_code" = "200" ] || [ "$http_code" = "201" ]; then
            log "INFO" "✅ Akun Super Administrator berhasil dibuat!"
            echo ""
            echo -e "${GREEN}=== DETAIL AKUN SUPER ADMINISTRATOR ===${NC}"
            echo -e "${GREEN}Nama:${NC} $admin_name"
            echo -e "${GREEN}Username:${NC} $admin_username"
            echo -e "${GREEN}Email:${NC} $admin_email"
            echo -e "${GREEN}Role:${NC} Super Administrator"
            echo ""
            echo -e "${YELLOW}⚠️  Simpan informasi login ini dengan aman!${NC}"
            echo -e "${RED}🔒 Super Admin memiliki akses penuh ke sistem!${NC}"
            echo ""
        else
            log "ERROR" "Gagal membuat akun Super Administrator!"
            log "ERROR" "HTTP Code: $http_code"
            log "ERROR" "Response: $response_body"
            
            # Coba alternatif: buat langsung ke database
            log "INFO" "Mencoba membuat Super Admin melalui database langsung..."
            create_superadmin_direct
        fi
    else
        log "ERROR" "curl tidak tersedia. Mencoba membuat Super Admin melalui database langsung..."
        create_superadmin_direct
    fi
}

# Fungsi alternatif untuk membuat superadmin langsung ke database
create_superadmin_direct() {
    log "INFO" "Membuat Super Admin langsung ke database MongoDB..."
    
    # Cek apakah mongosh atau mongo tersedia
    local mongo_cmd=""
    if command -v mongosh &> /dev/null; then
        mongo_cmd="mongosh"
    elif command -v mongo &> /dev/null; then
        mongo_cmd="mongo"
    else
        log "ERROR" "MongoDB client (mongosh/mongo) tidak tersedia!"
        log "INFO" "Silakan install MongoDB client atau gunakan method lain."
        return 1
    fi
    
    # Load environment variables
    if [ -f ".env" ]; then
        source .env
    fi
    
    local mongo_uri=${MONGO_URI:-"mongodb://localhost:27017"}
    local mongo_db=${MONGO_NAME:-"loko"}
    
    # Generate ObjectID dan timestamp
    local object_id=$(date +%s | sha256sum | cut -c1-24)
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
    
    # Hash password (simple hash untuk demo - di production gunakan bcrypt)
    local hashed_password=$(echo -n "$admin_password" | sha256sum | cut -d' ' -f1)
    
    # MongoDB script
    local mongo_script="
    use $mongo_db;
    db.users.insertOne({
        _id: ObjectId(),
        name: '$admin_name',
        username: '$admin_username',
        email: '$admin_email',
        password: '$hashed_password',
        role_id: 'Administrator',
        is_verify: true,
        is_active: true,
        credits: 0,
        created_at: new Date(),
        updated_at: new Date()
    });
    "
    
    echo "$mongo_script" | $mongo_cmd "$mongo_uri" --quiet
    
    if [ $? -eq 0 ]; then
        log "INFO" "✅ Super Administrator berhasil dibuat langsung ke database!"
        echo ""
        echo -e "${GREEN}=== DETAIL AKUN SUPER ADMINISTRATOR ===${NC}"
        echo -e "${GREEN}Nama:${NC} $admin_name"
        echo -e "${GREEN}Username:${NC} $admin_username"
        echo -e "${GREEN}Email:${NC} $admin_email"
        echo -e "${GREEN}Role:${NC} Super Administrator"
        echo ""
        echo -e "${YELLOW}⚠️  Simpan informasi login ini dengan aman!${NC}"
        echo -e "${RED}🔒 Super Admin memiliki akses penuh ke sistem!${NC}"
        echo ""
    else
        log "ERROR" "Gagal membuat akun Super Administrator ke database!"
        return 1
    fi
}

# =============================================================================
# Help Function
# =============================================================================

show_help() {
    echo -e "${CYAN}"
    echo "============================================="
    echo "    LOKO BACKEND MANAGEMENT SCRIPT"
    echo "============================================="
    echo -e "${NC}"
    echo "Usage: $0 [COMMAND] [OPTIONS]"
    echo ""
    echo -e "${YELLOW}BUILD COMMANDS:${NC}"
    echo "  build                 Build aplikasi (native)"
    echo "  build-frontend        Build React frontend saja"
    echo "  build-backend         Build Go backend dengan embedded frontend"
    echo "  build-fullstack       Build frontend + backend (full stack)"
    echo "  build-native          Build native (frontend + backend sederhana)"
    echo "  build-all             Alias untuk build-fullstack"
    echo "  build-optimized       Build dengan optimasi"
    echo "  build-docker          Build dengan Docker Compose"
    echo "  rebuild               Rebuild Docker containers (force)"
    echo "  generate-docs         Generate Swagger documentation"
    echo ""
    echo -e "${YELLOW}RUN COMMANDS:${NC}"
    echo "  dev                   Jalankan dalam mode development (native)"
    echo "  prod                  Jalankan dalam mode production (native)"
    echo "  watch                 Jalankan dengan hot reload (air)"
    echo "  docker                Jalankan dengan Docker Compose"
    echo "  docker-build          Build dan jalankan dengan Docker Compose"
    echo ""
    echo -e "${YELLOW}CONTROL COMMANDS:${NC}"
    echo "  start                 Alias untuk 'prod'"
    echo "  stop                  Hentikan aplikasi (native)"
    echo "  stop-docker           Hentikan Docker containers"
    echo "  stop-all              Hentikan semua (native + Docker + kill ports + cleanup + rebuild)"
    echo "  kill-ports            Hentikan proses di port tertentu (8000, 3000, 5173, 8080, 9000)"
    echo "  restart               Restart aplikasi (native)"
    echo "  restart-docker        Restart Docker containers"
    echo "  restart-all           Restart semua dengan pilihan mode"
    echo "  status                Tampilkan status aplikasi dan Docker"
    echo ""
    echo -e "${YELLOW}MAINTENANCE COMMANDS:${NC}"
    echo "  install               Install dependencies"
    echo "  clean                 Bersihkan file temporary"
    echo "  cleanup-all           Bersihkan semua file temporary, cache, dan build artifacts"
    echo "  rebuild-all           Rebuild semua komponen (install deps + build frontend + backend)"
    echo "  test                  Jalankan tests"
    echo "  test-coverage         Jalankan tests dengan coverage"
    echo ""
    echo -e "${YELLOW}LOG COMMANDS:${NC}"
    echo "  logs [lines]          Tampilkan log native (default: 50 lines)"
    echo "  logs-docker [service] [lines]  Tampilkan Docker logs"
    echo "  error-logs [lines]    Tampilkan error log (default: 50 lines)"
    echo "  follow-logs           Follow log real-time (native)"
    echo "  follow-logs-docker [service]   Follow Docker logs real-time"
    echo ""
    echo -e "${YELLOW}DATABASE COMMANDS:${NC}"
    echo "  check-db              Cek koneksi database"
    echo "  clean-db              Reset database (HAPUS SEMUA DATA)"
    echo ""
    echo -e "${YELLOW}POSTGRESQL MANAGEMENT:${NC}"
    echo "  postgres-up [env]     Start PostgreSQL services (env: prod|dev, default: prod)"
    echo "  postgres-down [env]   Stop PostgreSQL services"
    echo "  postgres-restart [env] Restart PostgreSQL services"
    echo "  postgres-logs [env]   Show PostgreSQL logs"
    echo "  postgres-build [env]  Build and start PostgreSQL services"
    echo "  postgres-clean [env]  Clean PostgreSQL services (remove containers/volumes)"
    echo "  postgres-shell [env]  Connect to PostgreSQL shell"
    echo "  postgres-backup [env] Backup PostgreSQL database"
    echo "  postgres-restore [env] [file] Restore PostgreSQL database from backup"
    echo "  postgres-status [env] Show PostgreSQL services status"
    echo "  validate-migration    Validate PostgreSQL migration setup"
    echo "  test-connection       Test PostgreSQL database connection"
    echo ""
    echo -e "${YELLOW}ENVIRONMENT COMMANDS:${NC}"
    echo "  setup-env             Setup environment dari .env.example"
    echo "  validate-env          Validasi environment variables"
    echo "  backup-env            Backup file .env"
    echo ""
    echo -e "${YELLOW}MONITORING COMMANDS:${NC}"
    echo "  monitor               Tampilkan system monitoring"
    echo "  health-check          Jalankan health check"
    echo "  performance           Tampilkan performance metrics"
    echo ""
    echo -e "${YELLOW}BACKUP COMMANDS:${NC}"
    echo "  backup                Backup project files"
    echo "  cleanup-backups       Cleanup backup files lama"
    echo ""
    echo -e "${YELLOW}GIT COMMANDS:${NC}"
    echo "  git-push \"message\"    Commit dan push dengan build check"
    echo ""
    echo -e "${YELLOW}ADMIN MANAGEMENT:${NC}"
    echo "  create-admin          Buat akun administrator"
    echo "  create-superadmin     Buat akun super administrator"
    echo "  list-admins           Tampilkan daftar administrator"
    echo ""
    echo -e "${YELLOW}OTHER COMMANDS:${NC}"
    echo "  help                  Tampilkan help ini"
    echo ""
    echo -e "${CYAN}Examples:${NC}"
    echo "  $0 setup-env          # Setup environment pertama kali"
    echo "  $0 build-fullstack    # Build frontend + backend (recommended)"
    echo "  $0 build-native       # Build native (frontend + backend sederhana)"
    echo "  $0 build-frontend     # Build React frontend saja"
    echo "  $0 build-backend      # Build Go backend dengan embedded frontend"
    echo "  $0 dev                # Jalankan development server (native)"
    echo "  $0 docker-build       # Build dan jalankan dengan Docker"
    echo "  $0 build-docker       # Build Docker containers"
    echo "  $0 rebuild            # Rebuild Docker containers (force)"
    echo "  $0 docker             # Jalankan Docker containers"
    echo "  $0 stop-all           # Hentikan semua services"
    echo "  $0 restart-all        # Restart dengan pilihan mode"
    echo "  $0 logs-docker        # Tampilkan Docker logs"
    echo "  $0 follow-logs-docker # Follow Docker logs real-time"
    echo "  $0 monitor            # Monitoring sistem"
    echo "  $0 health-check       # Cek kesehatan aplikasi"
    echo "  $0 backup             # Backup project"
    echo "  $0 git-push \"fix: bug fixes\"  # Commit dengan message"
    echo ""
    echo -e "${CYAN}PostgreSQL Examples:${NC}"
    echo "  $0 validate-migration # Validasi setup migrasi PostgreSQL"
    echo "  $0 postgres-up dev    # Start PostgreSQL development environment"
    echo "  $0 postgres-logs dev  # Lihat logs PostgreSQL development"
    echo "  $0 postgres-shell dev # Connect ke PostgreSQL shell (development)"
    echo "  $0 postgres-backup dev # Backup database development"
    echo "  $0 postgres-restore dev backup.sql # Restore database dari backup"
    echo "  $0 test-connection    # Test koneksi database PostgreSQL"
    echo ""
}

# =============================================================================
# PostgreSQL Docker Management Functions
# =============================================================================

# Function to get docker-compose -f infrastructure/docker/docker-compose.yaml file based on environment
get_compose_file() {
    local env=${1:-prod}
    if [ "$env" = "dev" ]; then
        echo "docker-compose.dev.yaml"
    else
        echo "infrastructure/docker/docker-compose.yaml"
    fi
}

# Function to get database connection info
get_db_info() {
    local env=${1:-prod}
    if [ "$env" = "dev" ]; then
        echo "postgres-dev loko_dev_user loko_dev_db 5433"
    else
        echo "postgres loko_user loko_db 5432"
    fi
}

# Function to start PostgreSQL services
postgres_up() {
    local env=${1:-prod}
    local compose_file=$(get_compose_file $env)
    
    log "INFO" "Starting Loko Backend PostgreSQL ($env environment)"
    log "INFO" "Using compose file: $compose_file"
    
    docker-compose -f infrastructure/docker/docker-compose.yaml -f $compose_file up -d
    
    log "INFO" "PostgreSQL services started successfully!"
    log "INFO" "Application will be available at: http://localhost:2000"
    
    if [ "$env" = "dev" ]; then
        log "INFO" "pgAdmin will be available at: http://localhost:8080"
        log "INFO" "pgAdmin credentials: admin@loko.dev / admin123"
    fi
}

# Function to stop PostgreSQL services
postgres_down() {
    local env=${1:-prod}
    local compose_file=$(get_compose_file $env)
    
    log "INFO" "Stopping Loko Backend PostgreSQL ($env environment)"
    docker-compose -f infrastructure/docker/docker-compose.yaml -f $compose_file down
    log "INFO" "PostgreSQL services stopped successfully!"
}

# Function to restart PostgreSQL services
postgres_restart() {
    local env=${1:-prod}
    local compose_file=$(get_compose_file $env)
    
    log "INFO" "Restarting Loko Backend PostgreSQL ($env environment)"
    docker-compose -f infrastructure/docker/docker-compose.yaml -f $compose_file restart
    log "INFO" "PostgreSQL services restarted successfully!"
}

# Function to show PostgreSQL logs
postgres_logs() {
    local env=${1:-prod}
    local compose_file=$(get_compose_file $env)
    
    log "INFO" "Showing logs for Loko Backend PostgreSQL ($env environment)"
    docker-compose -f infrastructure/docker/docker-compose.yaml -f $compose_file logs -f
}

# Function to build and start PostgreSQL services
postgres_build() {
    local env=${1:-prod}
    local compose_file=$(get_compose_file $env)
    
    log "INFO" "Building and starting Loko Backend PostgreSQL ($env environment)"
    docker-compose -f infrastructure/docker/docker-compose.yaml -f $compose_file up --build -d
    log "INFO" "PostgreSQL services built and started successfully!"
}

# Function to clean PostgreSQL services
postgres_clean() {
    local env=${1:-prod}
    local compose_file=$(get_compose_file $env)
    
    log "WARN" "Cleaning Loko Backend PostgreSQL ($env environment)"
    log "WARN" "This will remove all containers, networks, and volumes!"
    
    read -p "Are you sure? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        docker-compose -f infrastructure/docker/docker-compose.yaml -f $compose_file down -v --remove-orphans
        log "INFO" "PostgreSQL cleanup completed!"
    else
        log "INFO" "PostgreSQL cleanup cancelled."
    fi
}

# Function to connect to PostgreSQL shell
postgres_shell() {
    local env=${1:-prod}
    local db_info=($(get_db_info $env))
    local container=${db_info[0]}
    local user=${db_info[1]}
    local database=${db_info[2]}
    
    log "INFO" "Connecting to PostgreSQL ($env environment)"
    docker exec -it ${container} psql -U $user -d $database
}

# Function to backup PostgreSQL database
postgres_backup() {
    local env=${1:-prod}
    local db_info=($(get_db_info $env))
    local container=${db_info[0]}
    local user=${db_info[1]}
    local database=${db_info[2]}
    local backup_file="backup_${database}_$(date +%Y%m%d_%H%M%S).sql"
    
    log "INFO" "Backing up PostgreSQL database ($env environment)"
    docker exec $container pg_dump -U $user $database > $backup_file
    log "INFO" "Database backup saved to: $backup_file"
}

# Function to restore PostgreSQL database
postgres_restore() {
    local env=${1:-prod}
    local backup_file=${2}
    
    if [ -z "$backup_file" ]; then
        log "ERROR" "Please specify backup file path"
        echo "Usage: $0 postgres-restore [env] [backup_file]"
        return 1
    fi
    
    if [ ! -f "$backup_file" ]; then
        log "ERROR" "Backup file not found: $backup_file"
        return 1
    fi
    
    local db_info=($(get_db_info $env))
    local container=${db_info[0]}
    local user=${db_info[1]}
    local database=${db_info[2]}
    
    log "WARN" "Restoring PostgreSQL database ($env environment)"
    log "WARN" "This will overwrite the existing database!"
    
    read -p "Are you sure? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        docker exec -i $container psql -U $user $database < $backup_file
        log "INFO" "Database restored successfully!"
    else
        log "INFO" "Restore cancelled."
    fi
}

# Function to show PostgreSQL services status
postgres_status() {
    local env=${1:-prod}
    local compose_file=$(get_compose_file $env)
    
    log "INFO" "PostgreSQL Services Status ($env environment)"
    docker-compose -f infrastructure/docker/docker-compose.yaml -f $compose_file ps
}

# =============================================================================
# PostgreSQL Migration Validation Functions
# =============================================================================

# Function to validate PostgreSQL migration
validate_migration() {
    log "INFO" "🔍 Validating PostgreSQL Migration..."
    
    # 1. Check if required files exist
    log "INFO" "Checking required files..."
    local files=(
        "docker-compose.dev.yaml"
        ".env.dev"
        "init.sql"
        "POSTGRESQL_MIGRATION.md"
    )
    
    for file in "${files[@]}"; do
        if [ -f "$file" ]; then
            log "INFO" "✅ File $file exists"
        else
            log "ERROR" "❌ File $file missing"
            return 1
        fi
    done
    
    # 2. Check Go dependencies
    log "INFO" "Checking Go dependencies..."
    if go mod tidy; then
        log "INFO" "✅ Go dependencies updated"
    else
        log "ERROR" "❌ Go dependencies failed"
        return 1
    fi
    
    if go build .; then
        log "INFO" "✅ Go build successful"
    else
        log "ERROR" "❌ Go build failed"
        return 1
    fi
    
    if go vet ./...; then
        log "INFO" "✅ Go vet passed"
    else
        log "ERROR" "❌ Go vet failed"
        return 1
    fi
    
    # 3. Check Docker Compose syntax
    log "INFO" "Validating Docker Compose files..."
    if docker-compose -f infrastructure/docker/docker-compose.yaml -f docker-compose.yaml config > /dev/null 2>&1; then
        log "INFO" "✅ docker-compose.yaml syntax valid"
    else
        log "ERROR" "❌ docker-compose.yaml syntax invalid"
        return 1
    fi
    
    if docker-compose -f infrastructure/docker/docker-compose.yaml -f docker-compose.dev.yaml config > /dev/null 2>&1; then
        log "INFO" "✅ docker-compose.dev.yaml syntax valid"
    else
        log "ERROR" "❌ docker-compose.dev.yaml syntax invalid"
        return 1
    fi
    
    # 4. Check environment variables
    log "INFO" "Checking environment variables..."
    if [ -f ".env.dev" ]; then
        source .env.dev
        
        local required_vars=(
            "DB_TYPE"
            "DB_HOST"
            "DB_PORT"
            "DB_USER"
            "DB_PASS"
            "DB_NAME"
        )
        
        for var in "${required_vars[@]}"; do
            if [ -n "${!var}" ]; then
                log "INFO" "✅ Environment variable $var is set"
            else
                log "ERROR" "❌ Environment variable $var is missing"
                return 1
            fi
        done
        
        # Check if DB_TYPE is postgres
        if [ "$DB_TYPE" = "postgres" ]; then
            log "INFO" "✅ DB_TYPE is set to postgres"
        else
            log "ERROR" "❌ DB_TYPE should be 'postgres', got '$DB_TYPE'"
            return 1
        fi
    else
        log "ERROR" "❌ .env.dev file not found"
        return 1
    fi
    
    # 5. Check if PostgreSQL driver is available
    log "INFO" "Checking PostgreSQL driver..."
    if grep -q "gorm.io/driver/postgres" go.mod; then
        log "INFO" "✅ PostgreSQL driver found in go.mod"
    else
        log "ERROR" "❌ PostgreSQL driver not found in go.mod"
        return 1
    fi
    
    # 6. Test database connection (if Docker is available)
    log "INFO" "Testing database connection..."
    if command -v docker &> /dev/null; then
        # Check if PostgreSQL container is running
        if docker ps | grep -q postgres; then
            log "INFO" "✅ PostgreSQL container is running"
            
            # Test connection
            if [ -f "cmd/test-db-connection/main.go" ]; then
                if go run cmd/test-db-connection/main.go; then
                    log "INFO" "✅ Database connection test passed"
                else
                    log "WARN" "⚠️ Database connection test failed (container might be starting)"
                fi
            else
                log "WARN" "⚠️ Database connection test script not found"
            fi
        else
            log "WARN" "⚠️ PostgreSQL container not running"
            log "INFO" "To start PostgreSQL: $0 postgres-up dev"
        fi
    else
        log "WARN" "⚠️ Docker not available, skipping container checks"
    fi
    
    echo ""
    log "INFO" "Migration validation completed!"
    log "INFO" "Next steps:"
    echo "  1. Start PostgreSQL: $0 postgres-up dev"
    echo "  2. Test connection: go run cmd/test-db-connection/main.go"
    echo "  3. Start application: $0 dev"
    echo "  4. Check logs: $0 postgres-logs dev"
    echo ""
    log "INFO" "For more information, see POSTGRESQL_MIGRATION.md"
}

# Function to test PostgreSQL connection
test_postgres_connection() {
    log "INFO" "Testing PostgreSQL connection..."
    
    if [ -f "cmd/test-db-connection/main.go" ]; then
        go run cmd/test-db-connection/main.go
    else
        log "ERROR" "Database connection test script not found"
        return 1
    fi
}

# =============================================================================
# Main Function
# =============================================================================

main() {
    # Setup directories
    setup_directories
    
    # Parse command
    case "$1" in
        "deploy")
            deploy
            ;;
        "destroy")
            destroy
            ;;
        "build")
            build
            ;;
        "build-frontend")
            build_frontend
            ;;
        "build-backend")
            build_backend
            ;;
        "build-fullstack"|"build-all")
            build_fullstack
            ;;
        "build-native")
            build_native
            ;;
        "build-optimized")
            build_optimized
            ;;
        "generate-docs")
            generate_docs
            ;;
        "dev")
            check_dependencies
            run_dev
            ;;
        "prod"|"start")
            check_dependencies
            run_prod
            ;;
        "watch")
            check_dependencies
            run_watch
            ;;
        "docker")
            run_docker
            ;;
        "docker-build")
            run_docker_build
            ;;
        "build-docker")
            build_docker
            ;;
        "rebuild")
            rebuild
            ;;
        "stop")
            stop
            ;;
        "stop-docker")
            stop_docker
            ;;
        "stop-all")
            stop_all
            ;;
        "kill-ports")
            kill_ports
            ;;
        "cleanup-all")
            cleanup_all
            ;;
        "rebuild-all")
            rebuild_all
            ;;
        "restart")
            restart
            ;;
        "restart-docker")
            restart_docker
            ;;
        "restart-all")
            restart_all
            ;;
        "status")
            status
            ;;
        "install")
            install
            ;;
        "clean")
            clean
            ;;
        "clean-db")
            clean_db
            ;;
        "test")
            test
            ;;
        "test-coverage")
            test_coverage
            ;;
        "logs")
            logs "$2"
            ;;
        "logs-docker")
            logs_docker "$2" "$3"
            ;;
        "error-logs")
            error_logs "$2"
            ;;
        "follow-logs")
            follow_logs
            ;;
        "follow-logs-docker")
            follow_logs_docker "$2"
            ;;
        "check-db")
            check_db
            ;;
        "setup-env")
            setup_env
            ;;
        "validate-env")
            validate_env
            ;;
        "backup-env")
            backup_env
            ;;
        "monitor")
            monitor
            ;;
        "health-check")
            health_check
            ;;
        "performance")
            performance
            ;;
        "backup")
            backup
            ;;
        "cleanup-backups")
            cleanup_backups
            ;;
        "git-push")
            git_push "$2"
            ;;
        "create-admin")
            create_admin
            ;;
        "list-admins")
            list_admins
            ;;
        "create-superadmin")
            create_superadmin
            ;;
        "postgres-up")
            postgres_up "${2:-prod}"
            ;;
        "postgres-down")
            postgres_down "${2:-prod}"
            ;;
        "postgres-restart")
            postgres_restart "${2:-prod}"
            ;;
        "postgres-logs")
            postgres_logs "${2:-prod}"
            ;;
        "postgres-build")
            postgres_build "${2:-prod}"
            ;;
        "postgres-clean")
            postgres_clean "${2:-prod}"
            ;;
        "postgres-shell")
            postgres_shell "${2:-prod}"
            ;;
        "postgres-backup")
            postgres_backup "${2:-prod}"
            ;;
        "postgres-restore")
            postgres_restore "${2:-prod}" "$3"
            ;;
        "postgres-status")
            postgres_status "${2:-prod}"
            ;;
        "validate-migration")
            validate_migration
            ;;
        "test-connection")
            test_postgres_connection
            ;;
        "help"|"--help"|"-h"|"")
            show_help
            ;;
        *)
            echo -e "${RED}Error: Unknown command '$1'${NC}"
            echo "Run '$0 help' untuk melihat available commands."
            exit 1
            ;;
    esac
}

# Tampilkan banner
show_banner

# Jalankan main function
main "$@"